# Generated by Django 4.1.3 on 2025-04-24 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='grinchuser',
            managers=[
            ],
        ),
    ]
