# Generated by Django 4.1.7 on 2023-06-25 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picklist', '0001_initial'),
        ('users', '0002_alter_grinchuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grinchuser',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='picklist.route'),
        ),
    ]
