# Generated by Django 4.1.3 on 2025-05-11 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
        ('users', '0002_alter_grinchuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grinchuser',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='route.route'),
        ),
    ]
