# Generated by Django 4.1.3 on 2025-05-11 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('order_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=30)),
                ('abbrev', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
