# Generated by Django 4.1.7 on 2024-02-10 16:26

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('order_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=30)),
                ('abbrev', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PickList',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pickup_date', models.DateField()),
                ('first_name', models.CharField(blank=True, max_length=64, null=True)),
                ('last_name', models.CharField(blank=True, max_length=64, null=True)),
                ('home_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True)),
                ('email', models.EmailField(max_length=128)),
                ('street_address', models.CharField(max_length=140)),
                ('where_is_it', models.CharField(blank=True, max_length=30, null=True)),
                ('client_comment', models.CharField(blank=True, max_length=256, null=True)),
                ('admin_comment', models.CharField(blank=True, max_length=500, null=True)),
                ('got_money', models.BooleanField(default=False)),
                ('got_tree', models.BooleanField(default=False)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='picklist.route')),
            ],
        ),
    ]
