# Generated by Django 4.1.3 on 2025-05-11 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_grinchuser_route'),
        ('route', '0001_initial'),
        ('picklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picklist',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='route.route'),
        ),
        migrations.DeleteModel(
            name='Route',
        ),
    ]
