# Generated by Django 4.1.7 on 2023-03-02 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picklist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picklist',
            name='comments',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='picklist',
            name='PickupDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='picklist',
            name='orderid',
            field=models.IntegerField(),
        ),
    ]
