# Generated by Django 4.1.7 on 2023-03-04 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picklist', '0002_picklist_comments_alter_picklist_pickupdate_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RouteNotes',
        ),
        migrations.RenameField(
            model_name='picklist',
            old_name='comments',
            new_name='client_comment',
        ),
        migrations.RenameField(
            model_name='picklist',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='picklist',
            old_name='gotmoney',
            new_name='got_money',
        ),
        migrations.RenameField(
            model_name='picklist',
            old_name='gottree',
            new_name='got_tree',
        ),
        migrations.RenameField(
            model_name='picklist',
            old_name='homephone',
            new_name='home_phone',
        ),
        migrations.RenameField(
            model_name='picklist',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='picklist',
            old_name='orderid',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='picklist',
            old_name='PickupDate',
            new_name='pickup_date',
        ),
        migrations.RenameField(
            model_name='picklist',
            old_name='streetaddress',
            new_name='street_address',
        ),
        migrations.RenameField(
            model_name='picklist',
            old_name='whereisit',
            new_name='where_is_it',
        ),
        migrations.AddField(
            model_name='picklist',
            name='admin_comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
