# Generated by Django 4.1.7 on 2023-03-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picklist', '0003_delete_routenotes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picklist',
            name='order_id',
            field=models.IntegerField(unique=True),
        ),
    ]
