# Generated by Django 4.1.3 on 2025-11-03 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_route_created_at_route_updated_at'),
        ('picklist', '0004_alter_picklist_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picklist',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='route.route'),
        ),
    ]
