# Generated by Django 4.1.3 on 2025-11-03 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gis',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='gis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
